name: trend_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.12.1
  - et_xmlfile=2.0.0
  - fonttools=4.55.3
  - funcy=2.0
  - gensim=4.3.3
  - jinja2=3.1.4
  - joblib=1.4.2
  - kiwisolver=1.4.7
  - markupsafe=3.0.2
  - matplotlib=3.9.4
  - nltk=3.9.1
  - numexpr=2.10.2
  - numpy=1.26.4
  - openpyxl=3.1.5
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.0.0
  - pyldavis=3.4.1
  - pyparsing=3.2.0
  - python-dateutil=2.9.0
  - pytz=2024.2
  - regex=2024.11.6
  - scikit-learn=1.6.0
  - scipy=1.13.1
  - seaborn=0.13.2
  - setuptools=75.6.0
  - six=1.17.0
  - smart-open=7.0.5
  - threadpoolctl=3.5.0
  - tqdm=4.67.1
  - wrapt=1.17.0
  - pip